### ISSUE TITLE
Please release the recent GCC10 fixes

### ISSUE THREAD

**Issue by marcan** [drobilla/sord#2]
I just ran into an ardour/lilv crash and it took me a while to trace it to here and find out the recent GCC10-related updates solved it. It would be great if we could get a new tag so distros can pick this up instead of having to add a bunch of ad-hoc patches.

**Comment by drobilla** [comment]
That fix is actually wrong and has other problems, which is why I haven't released it yet.  I think I have a proper one now, though I'm not 100% sure.

What scenario was triggering the crash for you?

**Comment by marcan** [comment]
Just starting Ardour was doing it, and also sometimes lv2bench. valgrind showed uninitialized data being used inside sord, which would then sometimes crash.

**Comment by drobilla** [comment]
http://download.drobilla.net/sord-0.16.6.tar.bz2
