### ISSUE TITLE
Sord Typed literals output in triples look relative

### ISSUE THREAD

**Issue by gatemezing** [drobilla/sord#7]
Hello @drobilla , we are using this amazing library for a small project to generate RDF triples. I realize that for typed literals, the output looks like the URIs are relative. 
For example, I see the following output ` @prefix xsd: <http://www.w3.org/2001/XMLSchema#> . <http://www.w3.org/ns/sosa/hasSimpleResult> "03"^^<xsd:float> ` instead of something like this one `<http://www.w3.org/ns/sosa/hasSimpleResult> "03"^^xsd:float `.  Is it possible to generate something like the latter? 
Thanks for this amazing library.

**Comment by drobilla** [comment]
It looks like you are somehow setting the datatype to the _URI_ "xsd:float" and getting just that.  Since it's unfortunately impossible to distinguish prefixed names like this from URIs ("xsd:" is a syntactically valid URI scheme, if not an actual standard one), you have to be careful not to mix them up whenever you're passing strings.

My guess is you have a sord_new_uri(world, "xsd:float") in there somewhere, but I would have to see your code/etc to be able to tell exactly why/how.

Note that if you're simply generating triples (and only generating triples, i.e. you don't need a model for them), you're better off using serd directly as sord's really just in the way for that.

**Comment by gatemezing** [comment]
Hello @drobilla, sorry for the delay. 
Yes, we are using the sord_new_uri(world, "xsd:float"). See below a sample function below where we use it:
````c
void AddFactWithLiteralObject(SordModel* mod, char* s, char* p, char* o, char* g, char* datatype)
{
    SordWorld* world = sord_get_world(mod);
    SordNode* subject = sord_new_uri(world, (const uint8_t*)s);
    SordNode* predicate = sord_new_uri(world, (const uint8_t*)p);

    SordNode* datatypeNode = sord_new_uri(world, (const uint8_t*)datatype);
    //SordNode* datatypeNode = NULL;
    //SordNode* datatypeNode = createSordNodeLiteral(datatype,mod);
    char lang[] = "float";
    SordNode* object = sord_new_literal(world, datatypeNode, (const uint8_t*)o, NULL);

    SordNode* graph = sord_new_uri(world, (const uint8_t*)g);
    SordQuad quad = {subject, predicate, object, graph};

    if (!sord_ask(mod, subject, predicate, object, graph))
    {
        sord_add(mod, quad);
    }

    sord_node_free(world, subject);
    sord_node_free(world, predicate);
    sord_node_free(world, object);
    sord_node_free(world, datatypeNode);
    sord_node_free(world, graph);
}
````
However, I'll be really happy to find a different way to do it directly with SERD since we are just creating RDF triples from raw observations.

**Comment by drobilla** [comment]
> sord_new_uri(world, "xsd:float")

Right, so sord is doing exactly what you ask.  _Syntactically_, "xsd:float" is a valid URI with scheme "xsd", so that's what you get.

That said, yeah, for this sort of thing using serd directly makes more sense.

**Comment by drobilla** [comment]
> However, I'll be really happy to find a different way to do it directly with SERD since we are just creating RDF triples from raw observations.

Hopefully the header is clear enough, although it's a bit more low-level (to avoid memory allocation and such).  Let me know if you have any issues.  I'm in the process of redoing the APIs with the hindsight of a decade or so of experience, so any feedback about stuff that's confusing could be useful.

**Comment by gatemezing** [comment]
> Right, so sord is doing exactly what you ask. _Syntactically_, "xsd:float" is a valid URI with scheme "xsd", so that's what you get.
> 
> That said, yeah, for this sort of thing using serd directly makes more sense.

Oh I see. What you mean is to use for example **serdi** to write into Turtle again and see if that solve the final syntax output? WDYT?

**Comment by gatemezing** [comment]
> Hopefully the header is clear enough, although it's a bit more low-level (to avoid memory allocation and such). Let me know if you have any issues. I'm in the process of redoing the APIs with the hindsight of a decade or so of experience, so any feedback about stuff that's confusing could be useful.

Right! I'll see if I can manage that without issues. Great to hear that there are some refactoring coming up very soon. Don't forget to add JSON-LD writer/reader if possible in the new releases.

**Comment by drobilla** [comment]
> Oh I see. What you mean is to use for example serdi to write into Turtle again and see if that solve the final syntax output? WDYT?

There is no recovery except manual search/replace or something, the data is mangled.  It needs to be written correctly to begin with.

The short, easy, and unproblematic advice is: just always use full URIs in code.  If you're still having trouble, it'd probably be easier to just share your code. It'll take me about 15 seconds to point out what's wrong with a complete working example.

**Comment by drobilla** [comment]
There will not be JSON-LD in the next release.  It is much, much, much more complicated to implement.

Probably the major version after that.  I doubt it can be added without breaking the API again.

**Comment by drobilla** [comment]
If you're still having trouble, it'd probably be easier to just share your code.  It'll take me about 15 seconds to point out what's wrong with a complete working example.

**Comment by gatemezing** [comment]
> There will not be JSON-LD in the next release. It is much, much, much more complicated to implement.
> 
> Probably the major version after that. I doubt it can be added without breaking the API again.

I can easily understand, thanks a lot!

**Comment by gatemezing** [comment]
> > Oh I see. What you mean is to use for example serdi to write into Turtle again and see if that solve the final syntax output? WDYT?
> 
> There is no recovery except manual search/replace or something, the data is mangled. It needs to be written correctly to begin with.
> 
> The short, easy, and unproblematic advice is: just always use full URIs in code. If you're still having trouble, it'd probably be easier to just share your code. It'll take me about 15 seconds to point out what's wrong with a complete working example.

+1. That was the trick. It works! I guess I can close the issue

**Comment by gatemezing** [comment]
Problem fixed!
