### ISSUE TITLE
Is the quad usage of Sord output a trig document?

### ISSUE THREAD

**Issue by gatemezing** [drobilla/sord#8]
Hello @drobilla , I was wondering if the usage of the graph in a quad structure output a document conforms to the [W3C TriG specification? ](https://www.w3.org/TR/trig/). I am not sure as for now, I use .ttl extension for a mix of quads with named graphs and default graph. Thanks for your input.

**Comment by drobilla** [comment]
?

You have to specify the syntax when creating a writer.  If you set it up to write TriG (that is, pass `SERD_TRIG`), then naturally it writes TriG.

You definitely shouldn't be putting graphs in .ttl files in general.  That's not Turtle.
